baseURL = "https://genteng.bangunan.co/"
languageCode = "id"
title = "Agen Genteng | Jual Genteng Beton, Genteng Keramik, Genteng Oven"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Agen Genteng berkualitas - Jual Genteng Beton, Genteng Keramik, dan Genteng Oven dengan harga bersaing dan pengiriman free ongkir."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual genteng metal", "genteng beton", "genteng keramik", "genteng kaca", "genteng aspal", "genteng seng", "genteng murah", "pengiriman genteng free ongkir"]
  base_price = 5800
  price_range = 5000
  free_shipping = true
  materials = [
  "Genteng Metal",
  "Genteng Aspal",
  "Genteng Keramik",
  "Genteng Beton",
  "Genteng Kaca",
  "Genteng Seng"
  ]
  categories = ["Genteng Metal", "Genteng Aspal", "Genteng  Keramik", "Genteng Beton", "Genteng Kaca", "Genteng Seng"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Barang dapat ditukar dalam 1 hari jika tidak sesuai.",
  "Penggantian atau pengembalian gratis untuk barang dengan cacat produksi.",
  "Barang yang tidak sesuai pesanan dapat dikembalikan tanpa biaya tambahan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Agen Genteng Berkualitas"
  hero_description = "Kami menawarkan berbagai jenis genteng berkualitas seperti genteng beton, genteng keramik, dan genteng oven. Solusi ideal untuk atap rumah Anda, dengan bahan yang tahan lama dan desain yang estetik."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Genteng"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan genteng berkualitas tinggi dengan berbagai pilihan, harga bersaing, dan layanan pengiriman free ongkir. Juga konsultasi gratis untuk membantu Anda memilih genteng yang tepat untuk proyek konstruksi Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "genteng.bangunan.co menawarkan berbagai jenis genteng berkualitas seperti genteng beton, genteng keramik, dan genteng oven. Kami mengutamakan kepuasan pelanggan dengan produk yang tahan lama, estetis, dan harga yang bersaing. Pilih kami untuk melindungi dan memperindah rumah atau bangunan Anda dengan genteng terbaik."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Rudi|Hendra|Agus|Wawan|Fajar|Rio}"
  message = "{Saya membeli genteng beton dari genteng.bangunan.co untuk proyek rumah saya, dan hasilnya {sangat memuaskan|luar biasa}. Kualitas produk {sangat baik|terbaik} dan {tahan lama|kokoh}.|Produk genteng beton yang saya beli dari genteng.bangunan.co {sangat memuaskan|hebat}. Kualitasnya {tahan lama|kokoh} dan {berkualitas|mantap} untuk proyek rumah saya.}"
  response = "{Terima kasih atas kepercayaan Anda! Kami senang dapat menyediakan genteng {berkualitas|terbaik} untuk proyek rumah Anda.|Kami sangat menghargai kepercayaan Anda. Senang mendengar Anda puas dengan produk genteng kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Fitri|Lina|Diah|Maya|Nur}"
  message = "{genteng.bangunan.co {sangat membantu|memudahkan} dalam memilih genteng untuk rumah saya. Produk yang saya beli {berkualitas|terbaik} dan {sesuai|tepat} dengan kebutuhan saya.|Layanan dari genteng.bangunan.co sangat {membantu|baik}, produk genteng yang saya beli {berkualitas tinggi|hebat} dan sesuai dengan kebutuhan saya.}"
  response = "{Kami sangat menghargai ulasan Anda. Senang mendengar bahwa Anda puas dengan produk genteng dari kami.|Terima kasih atas ulasan positifnya. Kami senang dapat memenuhi kebutuhan genteng rumah Anda!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Galih|Rizal|Bambang|Faisal|Ali|Toni|Deni}"
  message = "{Produk genteng keramik dari genteng.bangunan.co {sangat estetis|indah} dan cocok untuk proyek perumahan saya. Proses pembelian dan pengirimannya juga {cepat|efisien}.|Genteng keramik dari genteng.bangunan.co {sangat cantik|elegan} dan sesuai untuk proyek perumahan saya. Pengirimannya {cepat|aman} dan tanpa kendala.}"
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan genteng yang {berkualitas|kokoh} dengan layanan terbaik.|Kami senang bisa bekerja sama dengan Anda. Terima kasih atas kepercayaannya!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Deni|Hendra|Toni|Wawan|Gilang|Ari|Benny|Yudi}"
  message = "{Saya {sangat puas|senang} dengan genteng oven dari genteng.bangunan.co. Kualitasnya {sangat baik|hebat} dan {tahan lama|kuat} untuk proyek saya.|Genteng oven dari genteng.bangunan.co {berkualitas|bagus}, dan hasilnya {tahan lama|kokoh} serta cocok untuk proyek rumah saya.}"
  response = "{Senang mendengar Anda puas dengan produk genteng kami. Terima kasih atas kepercayaannya!|Kami sangat menghargai kepercayaan Anda. Terima kasih telah memilih genteng kami!}"
  rating = 4.5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan genteng.bangunan.co {sangat memuaskan|luar biasa}. Produk genteng beton yang saya beli {berkualitas tinggi|kokoh} dan sesuai dengan {harapan|ekspektasi} saya.|Saya {senang|puas} dengan layanan dari genteng.bangunan.co. Produk genteng yang saya pasang {berkualitas tinggi|hebat} dan hasilnya {memuaskan|luar biasa}.}"
  response = "{Terima kasih! Kami senang dapat membantu mewujudkan proyek Anda dengan genteng {terbaik|berkualitas}.|Kami sangat menghargai ulasan Anda. Terima kasih telah mempercayakan proyek genteng Anda kepada kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Rio|Galih|Faisal|Yanto|Benny|Toni|Deni|Rizal|Wawan}"
  message = "{Genteng dari genteng.bangunan.co {sangat sesuai|tepat} dengan kebutuhan proyek renovasi rumah saya. Proses pengirimannya {cepat|aman|efisien} dan produknya {berkualitas tinggi|kokoh}.|Saya {terkesan|puas} dengan layanan dari genteng.bangunan.co. Genteng yang saya beli {berkualitas|kokoh} dan proses pengirimannya {cepat|aman}.}"
  response = "{Kami senang mendengar bahwa Anda puas dengan produk dan layanan kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah mempercayakan proyek genteng Anda kepada kami. Kami senang hasilnya sesuai dengan harapan Anda.}"
  rating = 4

[[params.tabelItems]]
  name = "Genteng Metal"
  price = "26.000/buah"
[[params.tabelItems]]
  name = "Genteng Aspal"
  price = "125.000/mÂ²"
[[params.tabelItems]]
  name = "Genteng Keramik"
  price = "9.800/buah"
[[params.tabelItems]]
  name = "Genteng Kaca"
  price = "8.800/buah"
[[params.tabelItems]]
  name = "Genteng Seng"
  price = "39.000/lembar"
[[params.tabelItems]]
  name = "Genteng Beton"
  price = "5.800/buah"

[params.appliList]
  "Genteng Metal" = "atap rumah minimalis, hunian modern"
  "Genteng Aspal" = "atap rumah tahan cuaca, hunian di daerah hujan tinggi"
  "Genteng Keramik" = "atap rumah bergaya klasik dan modern"
  "Genteng Kaca" = "pencahayaan alami pada atap rumah"
  "Genteng Seng" = "atap rumah tradisional atau rumah lawas"
  "Genteng Beton" = "atap rumah kuat dan tahan lama, bangunan besar"

[params.kegunaanList]
  "Genteng Metal" = "menambah estetika pada atap rumah minimalis dan modern"
  "Genteng Aspal" = "tahan terhadap cuaca ekstrem dan tahan api"
  "Genteng Keramik" = "tampilannya estetis dengan warna yang beragam"
  "Genteng Kaca" = "memaksimalkan pencahayaan alami pada rumah"
  "Genteng Seng" = "hemat biaya dan efektif untuk rumah tradisional"
  "Genteng Beton" = "kuat, tahan lama, cocok untuk rumah dan bangunan besar"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Agen Genteng Beton, Keramik & Oven | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"